In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


Introduction to tensors

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
MATRIX = torch.tensor([[7,8],[1,2]])
MATRIX

tensor([[7, 8],
        [1, 2]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[1]

tensor([1, 2])

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1,2,3,6],[3,2,2,8],[2,3,3,6]]])
TENSOR

tensor([[[1, 2, 3, 6],
         [3, 2, 2, 8],
         [2, 3, 3, 6]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 4])

###Random tensor

In [15]:
#create random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4966, 0.4461, 0.7930, 0.7379],
        [0.7639, 0.1686, 0.8176, 0.6038],
        [0.0867, 0.5153, 0.2348, 0.8294]])

In [16]:
random_tensor = torch.rand(4,3,4)
random_tensor

tensor([[[0.0489, 0.1300, 0.2789, 0.0795],
         [0.7802, 0.2945, 0.1407, 0.4277],
         [0.4804, 0.3922, 0.6707, 0.8485]],

        [[0.9117, 0.7717, 0.1658, 0.7934],
         [0.8445, 0.5726, 0.1431, 0.2811],
         [0.7081, 0.8422, 0.7903, 0.4580]],

        [[0.9379, 0.6753, 0.5257, 0.0041],
         [0.4001, 0.2809, 0.6251, 0.1452],
         [0.8361, 0.0630, 0.1349, 0.0019]],

        [[0.5732, 0.6231, 0.4140, 0.2878],
         [0.0391, 0.0997, 0.9323, 0.4070],
         [0.5853, 0.6355, 0.4533, 0.7177]]])

In [17]:
random_tensor.ndim

3

In [18]:
zeros = torch.zeros(3,4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#range

In [19]:
range_of_tensors = torch.arange(6,10)
range_of_tensors

tensor([6, 7, 8, 9])

In [20]:
#range of 2dim tensors
range_of_tensors = torch.arange(start=4,end=10)
print(range_of_tensors)
print(range_of_tensors.ndim)
print(range_of_tensors.shape)

tensor([4, 5, 6, 7, 8, 9])
1
torch.Size([6])


In [21]:
tensor_zeros = torch.zeros_like(input = range_of_tensors)
tensor_zeros

tensor([0, 0, 0, 0, 0, 0])

#Tensor Datatype


In [22]:
float_tensor = torch.tensor([3.0,6.0],dtype=None,
                            device=None,
                            requires_grad=False)
float_tensor
print(float_tensor.dtype)

torch.float32


In [23]:
float_16_tensor = torch.tensor([3.0,6.0],dtype=torch.float16,
                            device=None,
                            requires_grad=False)
float_16_tensor
print(float_16_tensor.dtype)
#

torch.float16


In [24]:
some_tensor = torch.rand(3,4)
print(f"Tensor: {some_tensor}")
print(f"Datatype: {some_tensor.dtype}")
print(f"Device: {some_tensor.device}")
print(f"shape: {some_tensor.shape}")

Tensor: tensor([[0.5348, 0.9105, 0.6556, 0.2163],
        [0.3821, 0.7168, 0.7329, 0.0731],
        [0.3784, 0.6766, 0.2151, 0.7850]])
Datatype: torch.float32
Device: cpu
shape: torch.Size([3, 4])


#Manipulating tensors

In [25]:
tensor_add = torch.tensor([1,2,3])
tensor_add +10

tensor([11, 12, 13])

In [26]:
tensor_add*10

tensor([10, 20, 30])

In [27]:
tensor_add-10

tensor([-9, -8, -7])

In [28]:
torch.mul(tensor_add,10)

tensor([10, 20, 30])

Matrix multiplication
* Element wise multiplication
* Matrix multiplication [dot product]

In [29]:
matrix1 = torch.tensor([2,3])
print(torch.mul(matrix1, 4))
matrix1

tensor([ 8, 12])


tensor([2, 3])

In [30]:
#Matrix multiplication
tensor1 = torch.tensor([1,2,3])
dotproduct_tensor = torch.matmul(tensor1,tensor1)
dotproduct_tensor


tensor(14)

In [31]:
%%time
value = 0
for i in range(len(tensor1)):
  value += tensor1[i]*tensor1[i]
  print(value)


tensor(1)
tensor(5)
tensor(14)
CPU times: user 2.06 ms, sys: 9 µs, total: 2.07 ms
Wall time: 3.06 ms


In [32]:
%%time
torch.matmul(tensor1,tensor1)




CPU times: user 66 µs, sys: 11 µs, total: 77 µs
Wall time: 79.4 µs


tensor(14)

@ stands for matrix multiplication

1. inner dimensions must match
(3,2) @ (3,2) wont work
(2,3) @ (3,2) will work
(3,2) @ (2,3) will work

* the resultung matrix has the shape of outer dimension
(2,3) @ (3,2) shaoe will be (2,2)




In [33]:
mat1 = torch.tensor([[1,2],[3,4],[5,6]])
print(mat1)
print(mat1.ndim)
print(mat1.shape)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
2
torch.Size([3, 2])


In [34]:
mat2 = torch.tensor([[1,2,3,3],[2,2,2,2],[33,3,3,3]])
mat2



tensor([[ 1,  2,  3,  3],
        [ 2,  2,  2,  2],
        [33,  3,  3,  3]])

In [35]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
#transpose - to fix tensor shape issues
tensor_B = tensor_B.T
print(tensor_B)
torch.mm(tensor_A,tensor_B)


tensor([[ 7,  8,  9],
        [10, 11, 12]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Tensors Aggregration


In [36]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [37]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [38]:
x.max(), torch.max(x)

(tensor(91), tensor(91))

torch.mean requires float32 dtype

In [39]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [40]:
torch.sum(x),x.sum()

(tensor(460), tensor(460))

#Positional min and max


In [41]:
x.argmin() # returns index position of minimum value occured


tensor(0)

In [42]:
x.argmax()

tensor(9)

In [43]:
x[0],x[9]

(tensor(1), tensor(91))

In [44]:
x = torch.arange(1,10)
x, x.shape


(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [56]:
x = torch.arange(1,55).reshape(2,3,3,3)
x, x.shape

(tensor([[[[ 1,  2,  3],
           [ 4,  5,  6],
           [ 7,  8,  9]],
 
          [[10, 11, 12],
           [13, 14, 15],
           [16, 17, 18]],
 
          [[19, 20, 21],
           [22, 23, 24],
           [25, 26, 27]]],
 
 
         [[[28, 29, 30],
           [31, 32, 33],
           [34, 35, 36]],
 
          [[37, 38, 39],
           [40, 41, 42],
           [43, 44, 45]],
 
          [[46, 47, 48],
           [49, 50, 51],
           [52, 53, 54]]]]),
 torch.Size([2, 3, 3, 3]))

##Reproducability (take random out of random)

In [1]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.7937, 0.0408, 0.9789, 0.1643],
        [0.9145, 0.7126, 0.1251, 0.7650],
        [0.6176, 0.7494, 0.1982, 0.0614]])
tensor([[0.3947, 0.4718, 0.2769, 0.5289],
        [0.3839, 0.7481, 0.9044, 0.0810],
        [0.9713, 0.2634, 0.0150, 0.3097]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [3]:
#lets make some random but reproducible
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
